package com.stockapp.userservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AppUserAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppUserAllPropertiesEquals(AppUser expected, AppUser actual) {
        assertAppUserAutoGeneratedPropertiesEquals(expected, actual);
        assertAppUserAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppUserAllUpdatablePropertiesEquals(AppUser expected, AppUser actual) {
        assertAppUserUpdatableFieldsEquals(expected, actual);
        assertAppUserUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppUserAutoGeneratedPropertiesEquals(AppUser expected, AppUser actual) {
        assertThat(actual)
            .as("Verify AppUser auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppUserUpdatableFieldsEquals(AppUser expected, AppUser actual) {
        assertThat(actual)
            .as("Verify AppUser relevant properties")
            .satisfies(a -> assertThat(a.getLogin()).as("check login").isEqualTo(expected.getLogin()))
            .satisfies(a -> assertThat(a.getPassword()).as("check password").isEqualTo(expected.getPassword()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getActivated()).as("check activated").isEqualTo(expected.getActivated()))
            .satisfies(a -> assertThat(a.getAccountStatus()).as("check accountStatus").isEqualTo(expected.getAccountStatus()))
            .satisfies(a -> assertThat(a.getEmailVerified()).as("check emailVerified").isEqualTo(expected.getEmailVerified()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getLastLoginDate()).as("check lastLoginDate").isEqualTo(expected.getLastLoginDate()))
            .satisfies(a ->
                assertThat(a.getLastPasswordChangeDate()).as("check lastPasswordChangeDate").isEqualTo(expected.getLastPasswordChangeDate())
            )
            .satisfies(a ->
                assertThat(a.getFailedLoginAttempts()).as("check failedLoginAttempts").isEqualTo(expected.getFailedLoginAttempts())
            )
            .satisfies(a -> assertThat(a.getAccountLockedUntil()).as("check accountLockedUntil").isEqualTo(expected.getAccountLockedUntil())
            )
            .satisfies(a -> assertThat(a.getPasswordResetToken()).as("check passwordResetToken").isEqualTo(expected.getPasswordResetToken())
            )
            .satisfies(a ->
                assertThat(a.getPasswordResetTokenExpiry())
                    .as("check passwordResetTokenExpiry")
                    .isEqualTo(expected.getPasswordResetTokenExpiry())
            )
            .satisfies(a ->
                assertThat(a.getEmailVerificationToken()).as("check emailVerificationToken").isEqualTo(expected.getEmailVerificationToken())
            )
            .satisfies(a ->
                assertThat(a.getEmailVerificationTokenExpiry())
                    .as("check emailVerificationTokenExpiry")
                    .isEqualTo(expected.getEmailVerificationTokenExpiry())
            )
            .satisfies(a -> assertThat(a.getTwoFactorEnabled()).as("check twoFactorEnabled").isEqualTo(expected.getTwoFactorEnabled()))
            .satisfies(a -> assertThat(a.getTwoFactorSecret()).as("check twoFactorSecret").isEqualTo(expected.getTwoFactorSecret()))
            .satisfies(a -> assertThat(a.getLastLoginIp()).as("check lastLoginIp").isEqualTo(expected.getLastLoginIp()))
            .satisfies(a -> assertThat(a.getLanguage()).as("check language").isEqualTo(expected.getLanguage()))
            .satisfies(a -> assertThat(a.getTimezone()).as("check timezone").isEqualTo(expected.getTimezone()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppUserUpdatableRelationshipsEquals(AppUser expected, AppUser actual) {
        assertThat(actual)
            .as("Verify AppUser relationships")
            .satisfies(a -> assertThat(a.getAuthorities()).as("check authorities").isEqualTo(expected.getAuthorities()));
    }
}
