package com.stockapp.userservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LoginHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLoginHistoryAllPropertiesEquals(LoginHistory expected, LoginHistory actual) {
        assertLoginHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertLoginHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLoginHistoryAllUpdatablePropertiesEquals(LoginHistory expected, LoginHistory actual) {
        assertLoginHistoryUpdatableFieldsEquals(expected, actual);
        assertLoginHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLoginHistoryAutoGeneratedPropertiesEquals(LoginHistory expected, LoginHistory actual) {
        assertThat(actual)
            .as("Verify LoginHistory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLoginHistoryUpdatableFieldsEquals(LoginHistory expected, LoginHistory actual) {
        assertThat(actual)
            .as("Verify LoginHistory relevant properties")
            .satisfies(a -> assertThat(a.getLoginTime()).as("check loginTime").isEqualTo(expected.getLoginTime()))
            .satisfies(a -> assertThat(a.getLoginMethod()).as("check loginMethod").isEqualTo(expected.getLoginMethod()))
            .satisfies(a -> assertThat(a.getIpAddress()).as("check ipAddress").isEqualTo(expected.getIpAddress()))
            .satisfies(a -> assertThat(a.getUserAgent()).as("check userAgent").isEqualTo(expected.getUserAgent()))
            .satisfies(a -> assertThat(a.getDeviceType()).as("check deviceType").isEqualTo(expected.getDeviceType()))
            .satisfies(a -> assertThat(a.getLocation()).as("check location").isEqualTo(expected.getLocation()))
            .satisfies(a -> assertThat(a.getSuccessful()).as("check successful").isEqualTo(expected.getSuccessful()))
            .satisfies(a -> assertThat(a.getFailureReason()).as("check failureReason").isEqualTo(expected.getFailureReason()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLoginHistoryUpdatableRelationshipsEquals(LoginHistory expected, LoginHistory actual) {
        assertThat(actual)
            .as("Verify LoginHistory relationships")
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()));
    }
}
