package com.stockapp.userservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NotificationSettingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationSettingAllPropertiesEquals(NotificationSetting expected, NotificationSetting actual) {
        assertNotificationSettingAutoGeneratedPropertiesEquals(expected, actual);
        assertNotificationSettingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationSettingAllUpdatablePropertiesEquals(NotificationSetting expected, NotificationSetting actual) {
        assertNotificationSettingUpdatableFieldsEquals(expected, actual);
        assertNotificationSettingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationSettingAutoGeneratedPropertiesEquals(NotificationSetting expected, NotificationSetting actual) {
        assertThat(actual)
            .as("Verify NotificationSetting auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationSettingUpdatableFieldsEquals(NotificationSetting expected, NotificationSetting actual) {
        assertThat(actual)
            .as("Verify NotificationSetting relevant properties")
            .satisfies(a -> assertThat(a.getEmailEnabled()).as("check emailEnabled").isEqualTo(expected.getEmailEnabled()))
            .satisfies(a -> assertThat(a.getSmsEnabled()).as("check smsEnabled").isEqualTo(expected.getSmsEnabled()))
            .satisfies(a -> assertThat(a.getPushEnabled()).as("check pushEnabled").isEqualTo(expected.getPushEnabled()))
            .satisfies(a -> assertThat(a.getInAppEnabled()).as("check inAppEnabled").isEqualTo(expected.getInAppEnabled()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationSettingUpdatableRelationshipsEquals(NotificationSetting expected, NotificationSetting actual) {
        assertThat(actual)
            .as("Verify NotificationSetting relationships")
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()));
    }
}
