package com.stockapp.userservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PasswordHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPasswordHistoryAllPropertiesEquals(PasswordHistory expected, PasswordHistory actual) {
        assertPasswordHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertPasswordHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPasswordHistoryAllUpdatablePropertiesEquals(PasswordHistory expected, PasswordHistory actual) {
        assertPasswordHistoryUpdatableFieldsEquals(expected, actual);
        assertPasswordHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPasswordHistoryAutoGeneratedPropertiesEquals(PasswordHistory expected, PasswordHistory actual) {
        assertThat(actual)
            .as("Verify PasswordHistory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPasswordHistoryUpdatableFieldsEquals(PasswordHistory expected, PasswordHistory actual) {
        assertThat(actual)
            .as("Verify PasswordHistory relevant properties")
            .satisfies(a -> assertThat(a.getPasswordHash()).as("check passwordHash").isEqualTo(expected.getPasswordHash()))
            .satisfies(a -> assertThat(a.getChangedDate()).as("check changedDate").isEqualTo(expected.getChangedDate()))
            .satisfies(a -> assertThat(a.getChangedBy()).as("check changedBy").isEqualTo(expected.getChangedBy()))
            .satisfies(a -> assertThat(a.getChangeReason()).as("check changeReason").isEqualTo(expected.getChangeReason()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPasswordHistoryUpdatableRelationshipsEquals(PasswordHistory expected, PasswordHistory actual) {
        assertThat(actual)
            .as("Verify PasswordHistory relationships")
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()));
    }
}
