package com.stockapp.userservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SessionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionAllPropertiesEquals(Session expected, Session actual) {
        assertSessionAutoGeneratedPropertiesEquals(expected, actual);
        assertSessionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionAllUpdatablePropertiesEquals(Session expected, Session actual) {
        assertSessionUpdatableFieldsEquals(expected, actual);
        assertSessionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionAutoGeneratedPropertiesEquals(Session expected, Session actual) {
        assertThat(actual)
            .as("Verify Session auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionUpdatableFieldsEquals(Session expected, Session actual) {
        assertThat(actual)
            .as("Verify Session relevant properties")
            .satisfies(a -> assertThat(a.getSessionId()).as("check sessionId").isEqualTo(expected.getSessionId()))
            .satisfies(a -> assertThat(a.getToken()).as("check token").isEqualTo(expected.getToken()))
            .satisfies(a -> assertThat(a.getRefreshToken()).as("check refreshToken").isEqualTo(expected.getRefreshToken()))
            .satisfies(a -> assertThat(a.getIpAddress()).as("check ipAddress").isEqualTo(expected.getIpAddress()))
            .satisfies(a -> assertThat(a.getUserAgent()).as("check userAgent").isEqualTo(expected.getUserAgent()))
            .satisfies(a -> assertThat(a.getLoginTime()).as("check loginTime").isEqualTo(expected.getLoginTime()))
            .satisfies(a -> assertThat(a.getExpiryTime()).as("check expiryTime").isEqualTo(expected.getExpiryTime()))
            .satisfies(a -> assertThat(a.getLastActivityTime()).as("check lastActivityTime").isEqualTo(expected.getLastActivityTime()))
            .satisfies(a -> assertThat(a.getDeviceId()).as("check deviceId").isEqualTo(expected.getDeviceId()))
            .satisfies(a -> assertThat(a.getDeviceName()).as("check deviceName").isEqualTo(expected.getDeviceName()))
            .satisfies(a -> assertThat(a.getDeviceType()).as("check deviceType").isEqualTo(expected.getDeviceType()))
            .satisfies(a -> assertThat(a.getOsName()).as("check osName").isEqualTo(expected.getOsName()))
            .satisfies(a -> assertThat(a.getOsVersion()).as("check osVersion").isEqualTo(expected.getOsVersion()))
            .satisfies(a -> assertThat(a.getBrowserName()).as("check browserName").isEqualTo(expected.getBrowserName()))
            .satisfies(a -> assertThat(a.getBrowserVersion()).as("check browserVersion").isEqualTo(expected.getBrowserVersion()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getIsTrustedDevice()).as("check isTrustedDevice").isEqualTo(expected.getIsTrustedDevice()))
            .satisfies(a -> assertThat(a.getLocation()).as("check location").isEqualTo(expected.getLocation()))
            .satisfies(a -> assertThat(a.getLogoutTime()).as("check logoutTime").isEqualTo(expected.getLogoutTime()))
            .satisfies(a -> assertThat(a.getRevokedAt()).as("check revokedAt").isEqualTo(expected.getRevokedAt()))
            .satisfies(a -> assertThat(a.getRevokedReason()).as("check revokedReason").isEqualTo(expected.getRevokedReason()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionUpdatableRelationshipsEquals(Session expected, Session actual) {
        assertThat(actual)
            .as("Verify Session relationships")
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()));
    }
}
