package com.stockapp.crawlservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CrawlJobStateAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCrawlJobStateAllPropertiesEquals(CrawlJobState expected, CrawlJobState actual) {
        assertCrawlJobStateAutoGeneratedPropertiesEquals(expected, actual);
        assertCrawlJobStateAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCrawlJobStateAllUpdatablePropertiesEquals(CrawlJobState expected, CrawlJobState actual) {
        assertCrawlJobStateUpdatableFieldsEquals(expected, actual);
        assertCrawlJobStateUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCrawlJobStateAutoGeneratedPropertiesEquals(CrawlJobState expected, CrawlJobState actual) {
        assertThat(actual)
            .as("Verify CrawlJobState auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCrawlJobStateUpdatableFieldsEquals(CrawlJobState expected, CrawlJobState actual) {
        assertThat(actual)
            .as("Verify CrawlJobState relevant properties")
            .satisfies(a -> assertThat(a.getSymbol()).as("check symbol").isEqualTo(expected.getSymbol()))
            .satisfies(a ->
                assertThat(a.getLastSuccessfulTimestamp())
                    .as("check lastSuccessfulTimestamp")
                    .isEqualTo(expected.getLastSuccessfulTimestamp())
            )
            .satisfies(a -> assertThat(a.getLastSyncStatus()).as("check lastSyncStatus").isEqualTo(expected.getLastSyncStatus()))
            .satisfies(a -> assertThat(a.getErrorLog()).as("check errorLog").isEqualTo(expected.getErrorLog()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCrawlJobStateUpdatableRelationshipsEquals(CrawlJobState expected, CrawlJobState actual) {
        // empty method
    }
}
