package com.stockapp.newsservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CompanyRefAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompanyRefAllPropertiesEquals(CompanyRef expected, CompanyRef actual) {
        assertCompanyRefAutoGeneratedPropertiesEquals(expected, actual);
        assertCompanyRefAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompanyRefAllUpdatablePropertiesEquals(CompanyRef expected, CompanyRef actual) {
        assertCompanyRefUpdatableFieldsEquals(expected, actual);
        assertCompanyRefUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompanyRefAutoGeneratedPropertiesEquals(CompanyRef expected, CompanyRef actual) {
        assertThat(actual)
            .as("Verify CompanyRef auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompanyRefUpdatableFieldsEquals(CompanyRef expected, CompanyRef actual) {
        assertThat(actual)
            .as("Verify CompanyRef relevant properties")
            .satisfies(a -> assertThat(a.getSymbol()).as("check symbol").isEqualTo(expected.getSymbol()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompanyRefUpdatableRelationshipsEquals(CompanyRef expected, CompanyRef actual) {
        // empty method
    }
}
