package com.stockapp.newsservice.domain;

import static com.stockapp.newsservice.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CompanyNewsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompanyNewsAllPropertiesEquals(CompanyNews expected, CompanyNews actual) {
        assertCompanyNewsAutoGeneratedPropertiesEquals(expected, actual);
        assertCompanyNewsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompanyNewsAllUpdatablePropertiesEquals(CompanyNews expected, CompanyNews actual) {
        assertCompanyNewsUpdatableFieldsEquals(expected, actual);
        assertCompanyNewsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompanyNewsAutoGeneratedPropertiesEquals(CompanyNews expected, CompanyNews actual) {
        assertThat(actual)
            .as("Verify CompanyNews auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompanyNewsUpdatableFieldsEquals(CompanyNews expected, CompanyNews actual) {
        assertThat(actual)
            .as("Verify CompanyNews relevant properties")
            .satisfies(a -> assertThat(a.getUuid()).as("check uuid").isEqualTo(expected.getUuid()))
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getSnippet()).as("check snippet").isEqualTo(expected.getSnippet()))
            .satisfies(a -> assertThat(a.getUrl()).as("check url").isEqualTo(expected.getUrl()))
            .satisfies(a -> assertThat(a.getImageUrl()).as("check imageUrl").isEqualTo(expected.getImageUrl()))
            .satisfies(a -> assertThat(a.getLanguage()).as("check language").isEqualTo(expected.getLanguage()))
            .satisfies(a -> assertThat(a.getPublishedAt()).as("check publishedAt").isEqualTo(expected.getPublishedAt()))
            .satisfies(a -> assertThat(a.getSource()).as("check source").isEqualTo(expected.getSource()))
            .satisfies(a -> assertThat(a.getKeywords()).as("check keywords").isEqualTo(expected.getKeywords()))
            .satisfies(a ->
                assertThat(a.getRelevanceScore())
                    .as("check relevanceScore")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getRelevanceScore())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompanyNewsUpdatableRelationshipsEquals(CompanyNews expected, CompanyNews actual) {
        assertThat(actual)
            .as("Verify CompanyNews relationships")
            .satisfies(a -> assertThat(a.getCompany()).as("check company").isEqualTo(expected.getCompany()));
    }
}
