package com.stockapp.newsservice.domain;

import static com.stockapp.newsservice.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class NewsEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNewsEntityAllPropertiesEquals(NewsEntity expected, NewsEntity actual) {
        assertNewsEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertNewsEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNewsEntityAllUpdatablePropertiesEquals(NewsEntity expected, NewsEntity actual) {
        assertNewsEntityUpdatableFieldsEquals(expected, actual);
        assertNewsEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNewsEntityAutoGeneratedPropertiesEquals(NewsEntity expected, NewsEntity actual) {
        assertThat(actual)
            .as("Verify NewsEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNewsEntityUpdatableFieldsEquals(NewsEntity expected, NewsEntity actual) {
        assertThat(actual)
            .as("Verify NewsEntity relevant properties")
            .satisfies(a -> assertThat(a.getNewsUuid()).as("check newsUuid").isEqualTo(expected.getNewsUuid()))
            .satisfies(a -> assertThat(a.getSymbol()).as("check symbol").isEqualTo(expected.getSymbol()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getExchange()).as("check exchange").isEqualTo(expected.getExchange()))
            .satisfies(a -> assertThat(a.getCountry()).as("check country").isEqualTo(expected.getCountry()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getIndustry()).as("check industry").isEqualTo(expected.getIndustry()))
            .satisfies(a ->
                assertThat(a.getMatchScore())
                    .as("check matchScore")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMatchScore())
            )
            .satisfies(a ->
                assertThat(a.getSentimentScore())
                    .as("check sentimentScore")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getSentimentScore())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNewsEntityUpdatableRelationshipsEquals(NewsEntity expected, NewsEntity actual) {
        assertThat(actual)
            .as("Verify NewsEntity relationships")
            .satisfies(a -> assertThat(a.getNews()).as("check news").isEqualTo(expected.getNews()));
    }
}
