package com.stockapp.userservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RefreshTokenAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRefreshTokenAllPropertiesEquals(RefreshToken expected, RefreshToken actual) {
        assertRefreshTokenAutoGeneratedPropertiesEquals(expected, actual);
        assertRefreshTokenAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRefreshTokenAllUpdatablePropertiesEquals(RefreshToken expected, RefreshToken actual) {
        assertRefreshTokenUpdatableFieldsEquals(expected, actual);
        assertRefreshTokenUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRefreshTokenAutoGeneratedPropertiesEquals(RefreshToken expected, RefreshToken actual) {
        assertThat(actual)
            .as("Verify RefreshToken auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRefreshTokenUpdatableFieldsEquals(RefreshToken expected, RefreshToken actual) {
        assertThat(actual)
            .as("Verify RefreshToken relevant properties")
            .satisfies(a -> assertThat(a.getToken()).as("check token").isEqualTo(expected.getToken()))
            .satisfies(a -> assertThat(a.getExpiryDate()).as("check expiryDate").isEqualTo(expected.getExpiryDate()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getUsedDate()).as("check usedDate").isEqualTo(expected.getUsedDate()))
            .satisfies(a -> assertThat(a.getIpAddress()).as("check ipAddress").isEqualTo(expected.getIpAddress()))
            .satisfies(a -> assertThat(a.getUserAgent()).as("check userAgent").isEqualTo(expected.getUserAgent()))
            .satisfies(a -> assertThat(a.getDeviceId()).as("check deviceId").isEqualTo(expected.getDeviceId()))
            .satisfies(a -> assertThat(a.getRevoked()).as("check revoked").isEqualTo(expected.getRevoked()))
            .satisfies(a -> assertThat(a.getRevokedDate()).as("check revokedDate").isEqualTo(expected.getRevokedDate()))
            .satisfies(a -> assertThat(a.getRevokedReason()).as("check revokedReason").isEqualTo(expected.getRevokedReason()))
            .satisfies(a -> assertThat(a.getReplacedByToken()).as("check replacedByToken").isEqualTo(expected.getReplacedByToken()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRefreshTokenUpdatableRelationshipsEquals(RefreshToken expected, RefreshToken actual) {
        assertThat(actual)
            .as("Verify RefreshToken relationships")
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()));
    }
}
