package com.stockapp.userservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WatchlistItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWatchlistItemAllPropertiesEquals(WatchlistItem expected, WatchlistItem actual) {
        assertWatchlistItemAutoGeneratedPropertiesEquals(expected, actual);
        assertWatchlistItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWatchlistItemAllUpdatablePropertiesEquals(WatchlistItem expected, WatchlistItem actual) {
        assertWatchlistItemUpdatableFieldsEquals(expected, actual);
        assertWatchlistItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWatchlistItemAutoGeneratedPropertiesEquals(WatchlistItem expected, WatchlistItem actual) {
        assertThat(actual)
            .as("Verify WatchlistItem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWatchlistItemUpdatableFieldsEquals(WatchlistItem expected, WatchlistItem actual) {
        assertThat(actual)
            .as("Verify WatchlistItem relevant properties")
            .satisfies(a -> assertThat(a.getSymbol()).as("check symbol").isEqualTo(expected.getSymbol()))
            .satisfies(a -> assertThat(a.getAddedAt()).as("check addedAt").isEqualTo(expected.getAddedAt()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWatchlistItemUpdatableRelationshipsEquals(WatchlistItem expected, WatchlistItem actual) {
        assertThat(actual)
            .as("Verify WatchlistItem relationships")
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()));
    }
}
