package com.stockapp.stockservice.domain;

import static com.stockapp.stockservice.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class FinancialAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFinancialAllPropertiesEquals(Financial expected, Financial actual) {
        assertFinancialAutoGeneratedPropertiesEquals(expected, actual);
        assertFinancialAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFinancialAllUpdatablePropertiesEquals(Financial expected, Financial actual) {
        assertFinancialUpdatableFieldsEquals(expected, actual);
        assertFinancialUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFinancialAutoGeneratedPropertiesEquals(Financial expected, Financial actual) {
        assertThat(actual)
            .as("Verify Financial auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFinancialUpdatableFieldsEquals(Financial expected, Financial actual) {
        assertThat(actual)
            .as("Verify Financial relevant properties")
            .satisfies(a -> assertThat(a.getSymbol()).as("check symbol").isEqualTo(expected.getSymbol()))
            .satisfies(a -> assertThat(a.getYear()).as("check year").isEqualTo(expected.getYear()))
            .satisfies(a -> assertThat(a.getFrequency()).as("check frequency").isEqualTo(expected.getFrequency()))
            .satisfies(a -> assertThat(a.getStatementType()).as("check statementType").isEqualTo(expected.getStatementType()))
            .satisfies(a ->
                assertThat(a.getTotalAssets())
                    .as("check totalAssets")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalAssets())
            )
            .satisfies(a ->
                assertThat(a.getTotalLiabilities())
                    .as("check totalLiabilities")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalLiabilities())
            )
            .satisfies(a ->
                assertThat(a.getTotalEquity())
                    .as("check totalEquity")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalEquity())
            )
            .satisfies(a ->
                assertThat(a.getRevenue()).as("check revenue").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getRevenue())
            )
            .satisfies(a ->
                assertThat(a.getNetIncome()).as("check netIncome").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getNetIncome())
            )
            .satisfies(a ->
                assertThat(a.getOperatingCashFlow())
                    .as("check operatingCashFlow")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getOperatingCashFlow())
            )
            .satisfies(a -> assertThat(a.getFilingDate()).as("check filingDate").isEqualTo(expected.getFilingDate()))
            .satisfies(a -> assertThat(a.getFiscalDateEnding()).as("check fiscalDateEnding").isEqualTo(expected.getFiscalDateEnding()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFinancialUpdatableRelationshipsEquals(Financial expected, Financial actual) {
        assertThat(actual)
            .as("Verify Financial relationships")
            .satisfies(a -> assertThat(a.getCompany()).as("check company").isEqualTo(expected.getCompany()));
    }
}
