package com.stockapp.stockservice.domain;

import static com.stockapp.stockservice.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class HistoricalPriceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoricalPriceAllPropertiesEquals(HistoricalPrice expected, HistoricalPrice actual) {
        assertHistoricalPriceAutoGeneratedPropertiesEquals(expected, actual);
        assertHistoricalPriceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoricalPriceAllUpdatablePropertiesEquals(HistoricalPrice expected, HistoricalPrice actual) {
        assertHistoricalPriceUpdatableFieldsEquals(expected, actual);
        assertHistoricalPriceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoricalPriceAutoGeneratedPropertiesEquals(HistoricalPrice expected, HistoricalPrice actual) {
        assertThat(actual)
            .as("Verify HistoricalPrice auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoricalPriceUpdatableFieldsEquals(HistoricalPrice expected, HistoricalPrice actual) {
        assertThat(actual)
            .as("Verify HistoricalPrice relevant properties")
            .satisfies(a -> assertThat(a.getSymbol()).as("check symbol").isEqualTo(expected.getSymbol()))
            .satisfies(a -> assertThat(a.getDatetime()).as("check datetime").isEqualTo(expected.getDatetime()))
            .satisfies(a -> assertThat(a.getInterval()).as("check interval").isEqualTo(expected.getInterval()))
            .satisfies(a -> assertThat(a.getOpen()).as("check open").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getOpen()))
            .satisfies(a -> assertThat(a.getHigh()).as("check high").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getHigh()))
            .satisfies(a -> assertThat(a.getLow()).as("check low").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getLow()))
            .satisfies(a -> assertThat(a.getClose()).as("check close").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getClose()))
            .satisfies(a -> assertThat(a.getVolume()).as("check volume").isEqualTo(expected.getVolume()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoricalPriceUpdatableRelationshipsEquals(HistoricalPrice expected, HistoricalPrice actual) {
        assertThat(actual)
            .as("Verify HistoricalPrice relationships")
            .satisfies(a -> assertThat(a.getCompany()).as("check company").isEqualTo(expected.getCompany()));
    }
}
