package com.stockapp.stockservice.domain;

import static com.stockapp.stockservice.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class IntradayQuoteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntradayQuoteAllPropertiesEquals(IntradayQuote expected, IntradayQuote actual) {
        assertIntradayQuoteAutoGeneratedPropertiesEquals(expected, actual);
        assertIntradayQuoteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntradayQuoteAllUpdatablePropertiesEquals(IntradayQuote expected, IntradayQuote actual) {
        assertIntradayQuoteUpdatableFieldsEquals(expected, actual);
        assertIntradayQuoteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntradayQuoteAutoGeneratedPropertiesEquals(IntradayQuote expected, IntradayQuote actual) {
        assertThat(actual)
            .as("Verify IntradayQuote auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntradayQuoteUpdatableFieldsEquals(IntradayQuote expected, IntradayQuote actual) {
        assertThat(actual)
            .as("Verify IntradayQuote relevant properties")
            .satisfies(a -> assertThat(a.getSymbol()).as("check symbol").isEqualTo(expected.getSymbol()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getExchange()).as("check exchange").isEqualTo(expected.getExchange()))
            .satisfies(a -> assertThat(a.getMicCode()).as("check micCode").isEqualTo(expected.getMicCode()))
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a -> assertThat(a.getDatetime()).as("check datetime").isEqualTo(expected.getDatetime()))
            .satisfies(a -> assertThat(a.getTimestamp()).as("check timestamp").isEqualTo(expected.getTimestamp()))
            .satisfies(a -> assertThat(a.getLastQuoteAt()).as("check lastQuoteAt").isEqualTo(expected.getLastQuoteAt()))
            .satisfies(a -> assertThat(a.getOpen()).as("check open").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getOpen()))
            .satisfies(a -> assertThat(a.getHigh()).as("check high").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getHigh()))
            .satisfies(a -> assertThat(a.getLow()).as("check low").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getLow()))
            .satisfies(a -> assertThat(a.getClose()).as("check close").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getClose()))
            .satisfies(a -> assertThat(a.getVolume()).as("check volume").isEqualTo(expected.getVolume()))
            .satisfies(a ->
                assertThat(a.getPreviousClose())
                    .as("check previousClose")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPreviousClose())
            )
            .satisfies(a ->
                assertThat(a.getChange()).as("check change").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getChange())
            )
            .satisfies(a ->
                assertThat(a.getPercentChange())
                    .as("check percentChange")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPercentChange())
            )
            .satisfies(a -> assertThat(a.getAverageVolume()).as("check averageVolume").isEqualTo(expected.getAverageVolume()))
            .satisfies(a -> assertThat(a.getIsMarketOpen()).as("check isMarketOpen").isEqualTo(expected.getIsMarketOpen()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntradayQuoteUpdatableRelationshipsEquals(IntradayQuote expected, IntradayQuote actual) {
        // empty method
    }
}
