package com.stockapp.stockservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RecommendationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecommendationAllPropertiesEquals(Recommendation expected, Recommendation actual) {
        assertRecommendationAutoGeneratedPropertiesEquals(expected, actual);
        assertRecommendationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecommendationAllUpdatablePropertiesEquals(Recommendation expected, Recommendation actual) {
        assertRecommendationUpdatableFieldsEquals(expected, actual);
        assertRecommendationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecommendationAutoGeneratedPropertiesEquals(Recommendation expected, Recommendation actual) {
        assertThat(actual)
            .as("Verify Recommendation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecommendationUpdatableFieldsEquals(Recommendation expected, Recommendation actual) {
        assertThat(actual)
            .as("Verify Recommendation relevant properties")
            .satisfies(a -> assertThat(a.getPeriod()).as("check period").isEqualTo(expected.getPeriod()))
            .satisfies(a -> assertThat(a.getBuy()).as("check buy").isEqualTo(expected.getBuy()))
            .satisfies(a -> assertThat(a.getHold()).as("check hold").isEqualTo(expected.getHold()))
            .satisfies(a -> assertThat(a.getSell()).as("check sell").isEqualTo(expected.getSell()))
            .satisfies(a -> assertThat(a.getStrongBuy()).as("check strongBuy").isEqualTo(expected.getStrongBuy()))
            .satisfies(a -> assertThat(a.getStrongSell()).as("check strongSell").isEqualTo(expected.getStrongSell()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecommendationUpdatableRelationshipsEquals(Recommendation expected, Recommendation actual) {
        assertThat(actual)
            .as("Verify Recommendation relationships")
            .satisfies(a -> assertThat(a.getCompany()).as("check company").isEqualTo(expected.getCompany()));
    }
}
