package com.stockapp.stockservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PeerCompanyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPeerCompanyAllPropertiesEquals(PeerCompany expected, PeerCompany actual) {
        assertPeerCompanyAutoGeneratedPropertiesEquals(expected, actual);
        assertPeerCompanyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPeerCompanyAllUpdatablePropertiesEquals(PeerCompany expected, PeerCompany actual) {
        assertPeerCompanyUpdatableFieldsEquals(expected, actual);
        assertPeerCompanyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPeerCompanyAutoGeneratedPropertiesEquals(PeerCompany expected, PeerCompany actual) {
        assertThat(actual)
            .as("Verify PeerCompany auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPeerCompanyUpdatableFieldsEquals(PeerCompany expected, PeerCompany actual) {
        assertThat(actual)
            .as("Verify PeerCompany relevant properties")
            .satisfies(a -> assertThat(a.getPeerSymbol()).as("check peerSymbol").isEqualTo(expected.getPeerSymbol()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPeerCompanyUpdatableRelationshipsEquals(PeerCompany expected, PeerCompany actual) {
        assertThat(actual)
            .as("Verify PeerCompany relationships")
            .satisfies(a -> assertThat(a.getCompany()).as("check company").isEqualTo(expected.getCompany()));
    }
}
