package com.stockapp.stockservice.domain;

import static com.stockapp.stockservice.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class StockStatisticsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockStatisticsAllPropertiesEquals(StockStatistics expected, StockStatistics actual) {
        assertStockStatisticsAutoGeneratedPropertiesEquals(expected, actual);
        assertStockStatisticsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockStatisticsAllUpdatablePropertiesEquals(StockStatistics expected, StockStatistics actual) {
        assertStockStatisticsUpdatableFieldsEquals(expected, actual);
        assertStockStatisticsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockStatisticsAutoGeneratedPropertiesEquals(StockStatistics expected, StockStatistics actual) {
        assertThat(actual)
            .as("Verify StockStatistics auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockStatisticsUpdatableFieldsEquals(StockStatistics expected, StockStatistics actual) {
        assertThat(actual)
            .as("Verify StockStatistics relevant properties")
            .satisfies(a -> assertThat(a.getSymbol()).as("check symbol").isEqualTo(expected.getSymbol()))
            .satisfies(a -> assertThat(a.getAverageVolume()).as("check averageVolume").isEqualTo(expected.getAverageVolume()))
            .satisfies(a ->
                assertThat(a.getRolling1dChange())
                    .as("check rolling1dChange")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getRolling1dChange())
            )
            .satisfies(a ->
                assertThat(a.getRolling7dChange())
                    .as("check rolling7dChange")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getRolling7dChange())
            )
            .satisfies(a ->
                assertThat(a.getRollingChange())
                    .as("check rollingChange")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getRollingChange())
            )
            .satisfies(a ->
                assertThat(a.getFiftyTwoWeekLow())
                    .as("check fiftyTwoWeekLow")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getFiftyTwoWeekLow())
            )
            .satisfies(a ->
                assertThat(a.getFiftyTwoWeekHigh())
                    .as("check fiftyTwoWeekHigh")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getFiftyTwoWeekHigh())
            )
            .satisfies(a ->
                assertThat(a.getFiftyTwoWeekLowChange())
                    .as("check fiftyTwoWeekLowChange")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getFiftyTwoWeekLowChange())
            )
            .satisfies(a ->
                assertThat(a.getFiftyTwoWeekHighChange())
                    .as("check fiftyTwoWeekHighChange")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getFiftyTwoWeekHighChange())
            )
            .satisfies(a ->
                assertThat(a.getFiftyTwoWeekLowChangePercent())
                    .as("check fiftyTwoWeekLowChangePercent")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getFiftyTwoWeekLowChangePercent())
            )
            .satisfies(a ->
                assertThat(a.getFiftyTwoWeekHighChangePercent())
                    .as("check fiftyTwoWeekHighChangePercent")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getFiftyTwoWeekHighChangePercent())
            )
            .satisfies(a -> assertThat(a.getFiftyTwoWeekRange()).as("check fiftyTwoWeekRange").isEqualTo(expected.getFiftyTwoWeekRange()))
            .satisfies(a ->
                assertThat(a.getExtendedChange())
                    .as("check extendedChange")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getExtendedChange())
            )
            .satisfies(a ->
                assertThat(a.getExtendedPercentChange())
                    .as("check extendedPercentChange")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getExtendedPercentChange())
            )
            .satisfies(a ->
                assertThat(a.getExtendedPrice())
                    .as("check extendedPrice")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getExtendedPrice())
            )
            .satisfies(a -> assertThat(a.getExtendedTimestamp()).as("check extendedTimestamp").isEqualTo(expected.getExtendedTimestamp()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockStatisticsUpdatableRelationshipsEquals(StockStatistics expected, StockStatistics actual) {
        // empty method
    }
}
